# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18LWklpf4MN36WgS6BNTZjfu8khmxb1Ue
"""

#NUEVO
import streamlit as st
import pandas as pd
import numpy as np

st.set_page_config(page_title="Método TOPSIS", layout="wide")
st.title("Método TOPSIS")

# --- SELECTOR DE MÉTODO DE ENTRADA ---
metodo_entrada = st.radio(
    "¿Cómo prefieres ingresar los datos de tu tabla?",
    ["Agregar manualmente los datos de mi tabla (máximo 8 filas o columnas)", "Subir archivo Excel (.xlsx) de mi tabla"],
    horizontal=True
)

df_editado = None

# --- OPCIÓN 1: ENTRADA MANUAL ---
if metodo_entrada == "Agregar manualmente los datos de mi tabla (máximo 8 filas o columnas)": #Poner la matriz de manera manual.
    st.write("Configura el tamaño de tu tabla dadas tus opciones y criterios, para después llenar los datos directamente en la tabla de abajo.")
    col1, col2 = st.columns(2)
    with col1:
        num_alternativas = st.number_input("Número de Opciones (Filas)", min_value=2, max_value=8, value=4)
    with col2:
        num_criterios = st.number_input("Número de Criterios (Columnas)", min_value=2, max_value=8, value=5)

    alternativas_nombres = [f"Opción {i+1}" for i in range(num_alternativas)]
    criterios_nombres = [f"Criterio {chr(65+i)}" for i in range(num_criterios)] # Nombra A, B, C, D...

    df_vacio = pd.DataFrame(0.0, index=alternativas_nombres, columns=criterios_nombres)
    df_vacio.insert(0, "Nombre de cada Opción", alternativas_nombres)

    st.subheader("Llena la siguiente tabla con tus datos correspondientes")
    st.info("Esta tabla recibe el nombre de: Matriz de decisión. Haz doble clic en cualquier celda para editar el valor que le das a cada opción dado su criterio y agrega nombre a tus opciones.")

    df_editado = st.data_editor(df_vacio, hide_index=True, use_container_width=True)

# --- OPCIÓN 2: SUBIR ARCHIVO ---
else:
    st.subheader("Sube tu archivo")
    uploaded_file = st.file_uploader("Selecciona un archivo .xlsx", type=["xlsx"])

    if uploaded_file:
        df_subido = pd.read_excel(uploaded_file)
        st.info("Haz doble clic en cualquier celda para editar los valores de tu tabla si lo necesitas.")
        df_editado = st.data_editor(df_subido, hide_index=True, use_container_width=True)
    else:
        st.warning("Esperando archivo... , sube un archivo Excel para continuar.")
        st.stop() # Detener la ejecución hasta que se suba el archivo

# --- CONFIGURACIÓN DE CRITERIOS ---
if df_editado is not None:
    st.sidebar.header("Pesos sobre cada Criterios (todos los pesos deben sumar 1)")
    pesos = []
    impactos = []

    columnas_criterios = df_editado.columns[1:]

    for col in columnas_criterios:
        st.sidebar.subheader(f"{col}")
        # Ajustamos el valor por defecto dependiendo de si es manual o archivo
        valor_defecto = round(1.0/num_criterios, 2) if "manualmente" in metodo_entrada else 0.5
        w = st.sidebar.slider(f"Peso para {col}", 0.0, 1.0, valor_defecto, key=f"w_{col}")
        imp = st.sidebar.selectbox(f"Necesito: ({col})", ["Maximizar (+)", "Minimizar (-)"], key=f"imp_{col}")

        pesos.append(w)
        impactos.append(1 if "Maximizar" in imp else -1)

    # --- LÓGICA MATEMÁTICA TOPSIS ---
    if st.button("Obtener la mejor opción", type="primary"):

        # Validar pesos
        if sum(pesos) < 0.99 or sum(pesos) > 1.01:
             st.warning(f"La suma de los pesos es {sum(pesos):.2f}. Modifica para obtener 1.0.")

        # Paso 1: Extraer matriz. Usamos iloc[:, 0] para tomar siempre la primera columna sin importar su nombre
        alternativas = df_editado.iloc[:, 0].tolist()
        matriz = df_editado.iloc[:, 1:].to_numpy(dtype=float)

        pesos_np = np.array(pesos)
        tipo_c = np.array(impactos)

        # Paso 2: Normalizar matriz
        normas = np.linalg.norm(matriz, axis=0)
        normas = np.where(normas == 0, 1e-10, normas)
        matriz_normalizada = matriz / normas

        # Paso 3: Matriz ponderada
        matriz_ponderada = matriz_normalizada * pesos_np

        # Paso 4: Soluciones ideal y anti-ideal
        matriz_bc = matriz_ponderada * tipo_c
        ideal_pos = np.max(matriz_bc, axis=0)
        ideal_positiva = ideal_pos * tipo_c

        ideal_neg = np.min(matriz_bc, axis=0)
        ideal_negativa = ideal_neg * tipo_c

        # Paso 5: Distancia a las soluciones
        distancia_pos = np.linalg.norm(matriz_ponderada - ideal_positiva, axis=1)
        distancia_neg = np.linalg.norm(matriz_ponderada - ideal_negativa, axis=1)

        # Paso 6: Cercanía relativa
        cercania = distancia_neg / (distancia_pos + distancia_neg)

        # Paso 7: Ranking final
        df_resultados = pd.DataFrame({
            "Alternativa": alternativas,
            "Ranking (cercanía)": cercania
        }).sort_values(by="Ranking (cercanía)", ascending=False)

        df_resultados["Ranking"] = range(1, len(df_resultados) + 1)
        df_resultados = df_resultados[["Ranking", "Alternativa", "Ranking (cercanía)"]]

        # --- MOSTRAR RESULTADOS EN LA INTERFAZ ---
        st.success("Cálculo completado")

        st.subheader("Lista de mejores opciones (ordenadas de mayor a menor)")
        st.dataframe(df_resultados, hide_index=True, use_container_width=True)

        st.bar_chart(df_resultados.set_index("Alternativa")["Ranking (cercanía)"])

        with st.expander("Ver detalles del cálculo (Matriz Ponderada, Distancias, etc.)"):
            st.write("**Matriz Normalizada Ponderada:**")
            st.dataframe(pd.DataFrame(matriz_ponderada, index=alternativas, columns=columnas_criterios))

            st.write("**Distancias Ideales:**")
            df_distancias = pd.DataFrame({
                "Alternativa": alternativas,
                "S_i* (Ideal)": distancia_pos,
                "S_i- (Anti-ideal)": distancia_neg
            })
            st.dataframe(df_distancias, hide_index=True)
