# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yg0Pb-Cg2qxZjQmFIaJpFNxLPoRS_q6X
"""

import streamlit as st
import pandas as pd
import numpy as np

st.title("🚀 Analizador de Decisiones TOPSIS")
st.write("Configura el tamaño de tu matriz y llena los datos directamente en la tabla.")

# --- INTERFAZ DE USUARIO ---

col1, col2 = st.columns(2)
with col1:
    num_alternativas = st.number_input("Número de Alternativas (Filas)", min_value=2, max_value=20, value=4)
with col2:
    num_criterios = st.number_input("Número de Criterios (Columnas)", min_value=2, max_value=10, value=5)

alternativas_nombres = [f"Opción {i+1}" for i in range(num_alternativas)]
criterios_nombres = [f"Criterio {chr(65+i)}" for i in range(num_criterios)] # Nombra A, B, C, D...

df_vacio = pd.DataFrame(0.0, index=alternativas_nombres, columns=criterios_nombres)
df_vacio.insert(0, "Nombre de la Opción", alternativas_nombres)

st.subheader("📝 Llena tu matriz de decisión")
st.info("💡 Haz doble clic en cualquier celda para editar el nombre de la opción o su valor.")

# Tabla interactiva
df_editado = st.data_editor(df_vacio, hide_index=True, use_container_width=True)

st.sidebar.header("Configuración de Criterios")
pesos = []
impactos = []

columnas_criterios = df_editado.columns[1:]

for col in columnas_criterios:
    st.sidebar.subheader(f"Criterio: {col}")
    w = st.sidebar.slider(f"Peso para {col}", 0.0, 1.0, round(1.0/num_criterios, 2))
    imp = st.sidebar.selectbox(f"Tipo de impacto ({col})", ["Beneficio (+)", "Costo (-)"])

    pesos.append(w)
    impactos.append(1 if "Beneficio" in imp else -1)

# --- LÓGICA MATEMÁTICA TOPSIS ---

if st.button("Calcular Ranking TOPSIS", type="primary"):

    # Validar pesos
    if sum(pesos) < 0.99 or sum(pesos) > 1.01:
         st.warning(f"⚠️ Nota: La suma de los pesos es {sum(pesos):.2f}. En teoría debería ser 1.0.")

    # Paso 1: Extraer matriz y configuraciones de la interfaz
    alternativas = df_editado["Nombre de la Opción"].tolist()
    # Extraemos solo los números, ignorando la primera columna de nombres
    matriz = df_editado.iloc[:, 1:].to_numpy(dtype=float)

    pesos_np = np.array(pesos)
    tipo_c = np.array(impactos)

    # Paso 2: Normalizar matriz
    normas = np.linalg.norm(matriz, axis=0)
    # Evitar división por cero si el usuario deja una columna en ceros
    normas = np.where(normas == 0, 1e-10, normas)
    matriz_normalizada = matriz / normas

    # Paso 3: Matriz ponderada
    matriz_ponderada = matriz_normalizada * pesos_np

    # Paso 4: Soluciones ideal y anti-ideal
    matriz_bc = matriz_ponderada * tipo_c
    ideal_pos = np.max(matriz_bc, axis=0)
    ideal_positiva = ideal_pos * tipo_c

    ideal_neg = np.min(matriz_bc, axis=0)
    ideal_negativa = ideal_neg * tipo_c

    # Paso 5: Distancia a las soluciones
    distancia_pos = np.linalg.norm(matriz_ponderada - ideal_positiva, axis=1)
    distancia_neg = np.linalg.norm(matriz_ponderada - ideal_negativa, axis=1)

    # Paso 6: Cercanía relativa
    cercania = distancia_neg / (distancia_pos + distancia_neg)

    # Paso 7: Ranking final
    df_resultados = pd.DataFrame({
        "Alternativa": alternativas,
        "Cercanía (Desempeño)": cercania
    }).sort_values(by="Cercanía (Desempeño)", ascending=False)

    df_resultados["Ranking"] = range(1, len(df_resultados) + 1)
    # Reordenamos las columnas para que el Ranking salga primero
    df_resultados = df_resultados[["Ranking", "Alternativa", "Cercanía (Desempeño)"]]

    # --- MOSTRAR RESULTADOS EN LA INTERFAZ ---

    st.success("¡Cálculo completado exitosamente!")

    st.subheader("🏆 Ranking Final")
    st.dataframe(df_resultados, hide_index=True, use_container_width=True)

    # Opcional: Un gráfico de barras para que sea más visual
    st.bar_chart(df_resultados.set_index("Alternativa")["Cercanía (Desempeño)"])

    # Expandible para ver las matemáticas internas (a tu usuario le puede dar confianza ver esto)
    with st.expander("Ver detalles del cálculo (Matriz Ponderada, Distancias, etc.)"):
        st.write("**Matriz Normalizada Ponderada:**")
        st.dataframe(pd.DataFrame(matriz_ponderada, index=alternativas, columns=columnas_criterios))

        st.write("**Distancias Ideales:**")
        df_distancias = pd.DataFrame({
            "Alternativa": alternativas,
            "S_i* (Ideal)": distancia_pos,
            "S_i- (Anti-ideal)": distancia_neg
        })
        st.dataframe(df_distancias, hide_index=True)