# -*- coding: utf-8 -*-
"""app1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Do-iNRS4FlE1cKaumGT3Q2ArR3hD__g
"""

# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
import numpy as np

st.set_page_config(page_title="Método TOPSIS", layout="wide")
st.title("Método TOPSIS")

# --- SELECTOR DE MÉTODO DE ENTRADA ---
metodo_entrada = st.radio(
    "¿Cómo prefieres ingresar los datos de tu tabla?",
    ["Agregar manualmente los datos de mi tabla (máximo 8 filas o columnas)", "Subir archivo Excel (.xlsx) de mi tabla"],
    horizontal=True
)

# Inicializamos variables clave
df_editado = None
pesos_auto = None

# --- OPCIÓN 1: ENTRADA MANUAL ---
if "manualmente" in metodo_entrada: 
    st.write("Configura el tamaño de tu tabla dadas tus opciones y criterios...")
    col1, col2 = st.columns(2)
    with col1:
        num_alternativas = st.number_input("Número de Opciones (Filas)", min_value=2, max_value=8, value=4)
    with col2:
        num_criterios = st.number_input("Número de Criterios (Columnas)", min_value=2, max_value=8, value=5)

    alternativas_nombres = [f"Opción {i+1}" for i in range(num_alternativas)]
    criterios_nombres = [f"Criterio {chr(65+i)}" for i in range(num_criterios)]

    df_vacio = pd.DataFrame(0.0, index=alternativas_nombres, columns=criterios_nombres)
    df_vacio.insert(0, "Nombre de cada Opción", alternativas_nombres)
    
    st.subheader("Llena la siguiente tabla con tus datos correspondientes")
    df_editado = st.data_editor(df_vacio, hide_index=True, use_container_width=True)

# --- OPCIÓN 2: SUBIR ARCHIVO ---
else:
    st.subheader("Sube tu archivo")
    uploaded_file = st.file_uploader("Selecciona un archivo .xlsx", type=["xlsx"])

    if uploaded_file:
        excel_obj = pd.ExcelFile(uploaded_file)
        
        # MATRIZ (Primera hoja)
        df_subido = pd.read_excel(uploaded_file, sheet_name=0)
        st.info(f"Matriz de decisión cargada desde la hoja: '{excel_obj.sheet_names[0]}'")
        df_editado = st.data_editor(df_subido, hide_index=True, use_container_width=True)
        
        # PESOS (Segunda hoja - Ahora solo busca una columna)
        if len(excel_obj.sheet_names) > 1:
            try:
                df_conf = pd.read_excel(uploaded_file, sheet_name=1)
                # Solo tomamos la primera columna como los pesos
                pesos_auto = df_conf.iloc[:, 0].tolist()
                st.success(f"✅ Pesos detectados en la hoja: '{excel_obj.sheet_names[1]}'. Por favor, define qué necesitas maximizar o minimizar en el menú lateral.")
            except Exception as e:
                st.error("Se detectó una segunda hoja pero hubo un error al leer los pesos.")
    else:
        st.warning("Esperando archivo... , sube un archivo Excel para continuar.")
        st.stop()

# --- CONFIGURACIÓN DE CRITERIOS (BARRA LATERAL HÍBRIDA) ---
if df_editado is not None:
    pesos = []
    impactos = []
    columnas_criterios = df_editado.columns[1:]
    
    st.sidebar.header("Pesos sobre cada Criterio")
    espacio_nota = st.sidebar.empty() 
    st.sidebar.divider()

    # Recorremos cada criterio para poner sus controles
    for i, col in enumerate(columnas_criterios):
        st.sidebar.subheader(f"{col}")
        
        # 1. EL PESO (Automático del Excel o Manual con Slider)
        if pesos_auto is None:
            w = st.sidebar.slider(f"Peso para {col}", 0.0, 1.0, 0.0, key=f"w_{col}")
        else:
            # Extraemos el peso del Excel asegurándonos de que exista
            w = pesos_auto[i] if i < len(pesos_auto) else 0.0
            st.sidebar.info(f"**Peso asignado:** {w}")
            
        # 2. EL IMPACTO (Siempre manual a prueba de errores)
        imp = st.sidebar.selectbox(f"Necesito: ({col})", ["Maximizar (+)", "Minimizar (-)"], key=f"imp_{col}")
        
        pesos.append(w)
        impactos.append(1 if "Maximizar" in imp else -1)

    # Lógica del contador visual en la barra lateral
    suma_actual = sum(pesos)
    if round(suma_actual, 2) == 1.00:
        espacio_nota.success(f"Perfecto, has llegado a: {suma_actual:.2f} / 1.00")
    elif suma_actual > 1.00:
        espacio_nota.error(f"Has rebasado 1: {suma_actual:.2f} / 1.00")
    else:
        espacio_nota.warning(f"Llevas: {suma_actual:.2f} (Te faltan {1.0 - suma_actual:.2f})")
    
    st.sidebar.divider()

    # --- LÓGICA MATEMÁTICA TOPSIS ---
    if st.button("Obtener la mejor opción", type="primary"):
        if sum(pesos) < 0.98 or sum(pesos) > 1.02:
             st.error(f"La suma de los pesos es {sum(pesos):.2f}. Debe ser 1.0 para calcular.")
             st.stop()

        alternativas = df_editado.iloc[:, 0].tolist()
        matriz = df_editado.iloc[:, 1:].to_numpy(dtype=float)

        normas = np.linalg.norm(matriz, axis=0)
        normas = np.where(normas == 0, 1e-10, normas)
        matriz_ponderada = (matriz / normas) * np.array(pesos)

        matriz_bc = matriz_ponderada * np.array(impactos)
        ideal_pos = np.max(matriz_bc, axis=0) * np.array(impactos)
        ideal_neg = np.min(matriz_bc, axis=0) * np.array(impactos)

        distancia_pos = np.linalg.norm(matriz_ponderada - ideal_pos, axis=1)
        distancia_neg = np.linalg.norm(matriz_ponderada - ideal_neg, axis=1)
        cercania = distancia_neg / (distancia_pos + distancia_neg)

        df_resultados = pd.DataFrame({
            "Alternativa": alternativas,
            "Ranking (más cercano a la ideal)": cercania
        }).sort_values(by="Ranking (más cercano a la ideal)", ascending=False)

        df_resultados["Ranking"] = range(1, len(df_resultados) + 1)
        df_resultados = df_resultados[["Ranking", "Alternativa", "Ranking (más cercano a la ideal)"]]

        st.success("Cálculo completado")
        st.subheader("Lista de mejores opciones (ordenadas de mayor a menor)")
        st.dataframe(df_resultados, hide_index=True, use_container_width=True)
        st.bar_chart(df_resultados.set_index("Alternativa")["Ranking (más cercano a la ideal)"])

        with st.expander("Ver detalles del cálculo (Matriz Ponderada, Distancias, etc.)"):
            st.write("**Matriz Normalizada Ponderada:**")
            st.dataframe(pd.DataFrame(matriz_ponderada, index=alternativas, columns=columnas_criterios))

            st.write("**Distancias Ideales:**")
            df_distancias = pd.DataFrame({
                "Alternativa": alternativas,
                "S_i* (Ideal)": distancia_pos,
                "S_i- (Anti-ideal)": distancia_neg
            })
            st.dataframe(df_distancias, hide_index=True)
