# -*- coding: utf-8 -*-
"""app2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Do-iNRS4FlE1cKaumGT3Q2ArR3hD__g
"""

# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
import numpy as np

st.set_page_config(page_title="Método TOPSIS", layout="wide")
st.title("Método TOPSIS")
st.text("El método TOPSIS una técnica creada en 1981 por Hwang y Yoon. Este método consiste en evaluar las alternativas dada su similitud y cercanía a la mejor solución encontrada en tus datos, y con ello dar una lista de preferencia base tus opciones ordenadas de mayor a menor (llamada ranking). Para este proceso, es necesario que nos proporciones tus Opciones / Alternativas entre las que estás decidiendo y tus Propiedades sobre las cuales evaluaremos tus alternativas (estas propiedades serán llamadas Criterios de evaluación).")

# --- SELECTOR DE MÉTODO DE ENTRADA ---
metodo_entrada = st.radio(
    "¿Cómo prefieres ingresar los datos de tu tabla?",
    ["Agregar manualmente los datos de mi tabla (máximo 8 filas o columnas)", "Subir archivo Excel (.xlsx) de mi tabla"],
    horizontal=True
)

# Inicializamos variables clave
df_editado = None
pesos_auto = None
impactos_auto = None

# --- OPCIÓN 1: ENTRADA MANUAL ---
if "manualmente" in metodo_entrada: 
    st.write("Configura el tamaño de tu tabla dadas la cantidad de opciones y criterios de evaluación que desees...")
    col1, col2 = st.columns(2)
    with col1:
        num_alternativas = st.number_input("Número de Opciones (Filas)", min_value=2, max_value=8, value=4)
    with col2:
        num_criterios = st.number_input("Número de Criterios de evaluación (Columnas)", min_value=2, max_value=8, value=5)

    alternativas_nombres = [f"Opción {i+1}" for i in range(num_alternativas)]
    criterios_nombres = [f"Criterio {chr(65+i)}" for i in range(num_criterios)]

    df_vacio = pd.DataFrame(0.0, index=alternativas_nombres, columns=criterios_nombres)
    df_vacio.insert(0, "Nombre de cada Opción", alternativas_nombres)
    
    st.subheader("Llena la siguiente tabla con tus datos correspondientes")
    st.info("Esta tabla recibe el nombre de: Matriz de decisión. Haz doble clic en cualquier celda para editar el valor que le designas a cada opción dado su criterio de evaluación. No olvides agregar nombre a tus opciones.")

    df_editado = st.data_editor(df_vacio, hide_index=True, use_container_width=True)

# --- OPCIÓN 2: SUBIR ARCHIVO ---
else:
    st.subheader("Sube tu archivo. No olvides poner nombres a tus Opciones y Criterios de evaluación")
    # Nota: Aquí puedes completar el correo electrónico o dato de contacto al final del texto
    st.info("Si deseas que se agreguen automáticamente los Pesos o Valores de importancia de tus Criterios de evaluación, debes agregar una segunda hoja a tu archivo Excel y en ella debes colocar el peso de tus criterios. NOTA: debes colocar de arriba a abajo (es decir, únicamente en la columna A) el peso de tus criterios,  el primer peso que agregues será considerado el peso del criterio de evaluación 1, el segundo peso que agregues será considerado el peso del criterio de evaluación 2 y así sucesivamente. Cualquier duda contactar a: [Algún correo]")
    st.info("Si deseas agregar tus Pesos manualmente sube tu archivo Excel con únicamente una Hoja que incluya tu tabla de decisión. Una vez cargado tu archivo, en el menú lateral podrás agregar manualmente tus Pesos o Valores de importancia por criterio.")
    uploaded_file = st.file_uploader("Selecciona un archivo .xlsx", type=["xlsx"])

    if uploaded_file:
        excel_obj = pd.ExcelFile(uploaded_file)
        
        # MATRIZ (Primera hoja)
        df_subido = pd.read_excel(uploaded_file, sheet_name=0)
        st.info(f"Tabla con datos de decisión cargada desde la hoja: '{excel_obj.sheet_names[0]}'")
        df_editado = st.data_editor(df_subido, hide_index=True, use_container_width=True)
        
        # PESOS (Segunda hoja - Validación Avanzada)
        if len(excel_obj.sheet_names) > 1:
            try:
                # header=None evita que se pierda el primer peso si no le ponen título
                df_conf = pd.read_excel(uploaded_file, sheet_name=1, header=None)
                
                # Forzamos a que sean números y eliminamos celdas vacías o con texto
                pesos_brutos = pd.to_numeric(df_conf.iloc[:, 0], errors='coerce').dropna().tolist()
                
                if len(pesos_brutos) > 0:
                    pesos_auto = pesos_brutos
                    st.success(f"Hemos obtenido tus pesos de la hoja: '{excel_obj.sheet_names[1]}'. Por favor, en el menú lateral define para cada criterio si deseas maximizar o minimizar.")
                else:
                    st.warning("Se detectó una segunda hoja, pero está vacía o no tiene números. **Por favor cree la lista de pesos en orden sobre la columna A para que se carguen automáticamente.**")
            except Exception as e:
                st.warning("No se detectó una segunda hoja o hubo un error al leerla. **Por favor cree la segunda Hoja y haga una lista de pesos en orden sobre la columna A para que se carguen automáticamente. De lo contrario, agregue manualmente el peso de cada criterio.**")
    else: 
        st.warning("Esperando archivo... sube un archivo Excel para continuar.")
        st.stop()

# --- CONFIGURACIÓN DE CRITERIOS (BARRA LATERAL HÍBRIDA) ---
if df_editado is not None:
    pesos = []
    impactos = []
    columnas_criterios = df_editado.columns[1:]
    
    st.sidebar.header("Pesos o Valor de importancia sobre cada Criterio de evaluación")
    st.info("La suma de todos tus pesos debe ser exactamente 1")
    espacio_nota = st.sidebar.empty() 
    st.sidebar.divider()

    for i, col in enumerate(columnas_criterios):
        st.sidebar.subheader(f"{col}")
        
        # 1. EL PESO
        if pesos_auto is None:
            w = st.sidebar.slider(f"Peso para {col}", 0.0, 1.0, 0.0, key=f"w_{col}")
        else:
            w = pesos_auto[i] if i < len(pesos_auto) else 0.0
            st.sidebar.info(f"**Peso asignado:** {w}")
            
        # 2. EL IMPACTO
        imp = st.sidebar.selectbox(f"Necesito:", ["Maximizar (+)", "Minimizar (-)"], key=f"imp_{col}")
        
        pesos.append(w)
        impactos.append(1 if "Maximizar" in imp else -1)

    # Lógica del contador visual
    suma_actual = sum(pesos)
    if round(suma_actual, 2) == 1.00:
        espacio_nota.success(f"Perfecto, has llegado a: {suma_actual:.2f} / 1.00")
    elif suma_actual > 1.00:
        espacio_nota.error(f"Has rebasado 1, llevas: {suma_actual:.2f} / 1.00")
    else:
        espacio_nota.warning(f"Llevas: {suma_actual:.2f} (Te faltan {1.0 - suma_actual:.2f})")
    
    st.sidebar.divider()

    # --- LÓGICA MATEMÁTICA TOPSIS ---
    if st.button("Obtener el ranking de la mejor opción", type="primary"):
        if sum(pesos) < 0.98 or sum(pesos) > 1.02:
             st.error(f"La suma de los pesos es {sum(pesos):.2f}. Debe ser 1.0 para calcular.")
             st.stop()

        alternativas = df_editado.iloc[:, 0].tolist()
        matriz = df_editado.iloc[:, 1:].to_numpy(dtype=float)

        normas = np.linalg.norm(matriz, axis=0)
        normas = np.where(normas == 0, 1e-10, normas)
        matriz_ponderada = (matriz / normas) * np.array(pesos)

        matriz_bc = matriz_ponderada * np.array(impactos)
        ideal_pos = np.max(matriz_bc, axis=0) * np.array(impactos)
        ideal_neg = np.min(matriz_bc, axis=0) * np.array(impactos)

        distancia_pos = np.linalg.norm(matriz_ponderada - ideal_pos, axis=1)
        distancia_neg = np.linalg.norm(matriz_ponderada - ideal_neg, axis=1)
        cercania = distancia_neg / (distancia_pos + distancia_neg)

        df_resultados = pd.DataFrame({
            "Alternativa": alternativas,
            "Qué tan cerca está de la solución ideal": cercania
        }).sort_values(by="Qué tan cerca está de la solución ideal", ascending=False)

        df_resultados["Ranking"] = range(1, len(df_resultados) + 1)
        df_resultados = df_resultados[["Ranking", "Alternativa", "Qué tan cerca está de la solución ideal"]]

        st.success("Cálculo completado")
        st.subheader("Lista de mejores opciones (ordenadas de mayor a menor)")
        st.dataframe(df_resultados, hide_index=True, use_container_width=True)
        st.bar_chart(df_resultados.set_index("Alternativa")["Qué tan cerca está de la solución ideal"])

        with st.expander("Ver detalles del cálculo (Matriz Ponderada, Distancias, etc.)"):
            st.write("**Matriz Normalizada Ponderada:**")
            st.dataframe(pd.DataFrame(matriz_ponderada, index=alternativas, columns=columnas_criterios))

            st.write("**Distancias Ideales:**")
            df_distancias = pd.DataFrame({
                "Alternativa": alternativas,
                "S_i* (Ideal)": distancia_pos,
                "S_i- (Anti-ideal)": distancia_neg
            })
            st.dataframe(df_distancias, hide_index=True)
